table ALL_MEASURES
	lineageTag: 712670c8-cf0d-4b6f-9028-4f62962bbceb

	measure Total_Sales = SUM(SalesData[Sales])
		formatString: 0
		lineageTag: 35fb6151-6669-4263-a57a-cc378769a7af

	measure DS = CALCULATE([Total_Sales],SalesData[Sales Channel]="Direct")
		formatString: 0
		lineageTag: 94782f99-d486-4252-a55a-a2d48feefef0

	measure DS_Percent = DIVIDE([DS],[Total_Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3179342d-3355-4f98-b348-d10b30dc86c0

	measure DS_Punjab =
			CALCULATE([Total_Sales],
			            SalesData[Sales Channel]="Direct",
			            SalesData[State]="Punjab")
		formatString: 0
		lineageTag: 649908b2-dc9d-4356-888d-7aab0506c0ef

	measure Printer_Sales = CALCULATE([Total_Sales],KEEPFILTERS(SalesData[Product]="Printer"))
		formatString: 0
		lineageTag: ce19e94a-d97c-4e9b-852e-b8afe04175a8

	measure removeFilter = CALCULATE([Total_Sales],REMOVEFILTERS(SalesData[Product]))
		formatString: 0
		lineageTag: 460f28c3-ed2a-45d7-9c56-1bc6e7ec5e9a

	measure salesPercentage = DIVIDE([Total_Sales],[removeFilter])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: aee35101-e806-426d-94a4-e829925a2f94

	partition ALL_MEASURES = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

